name: Create ECR
description: Create and manage an Amazon ECR repository
author: https://github.com/seek-oss
requirements:
  - docker
configuration:
  properties:
    lifecycle-policy:
      type: string
    name:
      type: string
    scan-on-push:
      type: boolean
    repository-policy:
      type: string
    repository-tags-file:
      type: string
    image-tag-mutability:
      enum: ['MUTABLE', 'IMMUTABLE']
  required: ['name']
