#!/usr/bin/env bash

set -euo pipefail

basedir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

ecr_exists() {
  local repository_name="${1}"

  aws ecr describe-repositories \
    --repository-names "${repository_name}" \
    --output text \
    --query 'repositories[0].registryId'
}

upsert_ecr() {
  printenv
  
  local repository_name="${1}"

  if ! ecr_exists "${repository_name}"; then
    echo '--- Creating ECR repository'
    echo "Name: ${repository_name}"
    aws ecr create-repository --repository-name "${repository_name}"
  fi

  repository_policy_file="${BUILDKITE_PLUGIN_CREATE_ECR_REPOSITORY_POLICY:-}"
  if [[ ${repository_policy_file} != '' ]]; then
    echo '--- Setting ECR repository policy'
    echo "File: ${repository_policy_file}"
    aws ecr set-repository-policy \
      --repository-name "${repository_name}" \
      --policy-text "file://${repository_policy_file}"
  fi

  lifecycle_policy_file="${BUILDKITE_PLUGIN_CREATE_ECR_LIFECYCLE_POLICY:-"${basedir}/policies/default-lifecycle-policy.json"}"
  echo '--- Setting ECR lifecycle policy'
  echo "File: ${lifecycle_policy_file}"
  aws ecr put-lifecycle-policy \
  --repository-name "${repository_name}" \
  --lifecycle-policy-text "file://${lifecycle_policy_file}"

  if [[ "${BUILDKITE_PLUGIN_CREATE_ECR_SCAN_ON_PUSH:-}" =~ ^(true|on|1)$ ]]; then
    echo '--- Setting ECR image scanning configuration as Enabled'
    aws ecr put-image-scanning-configuration \
      --repository-name "${repository_name}" \
      --image-scanning-configuration \
      scanOnPush=true
  elif [[ "${BUILDKITE_PLUGIN_CREATE_ECR_SCAN_ON_PUSH:-}" =~ ^(false|off|0)$ ]]; then
    echo '--- Setting ECR image scanning configuration as disabled'
    aws ecr put-image-scanning-configuration \
      --repository-name "${repository_name}" \
      --image-scanning-configuration \
      scanOnPush=false
  fi
}

if [[ -z ${BUILDKITE_PLUGIN_CREATE_ECR_NAME:-} ]]; then
  echo "'name' property is required"
  exit 1
fi

repository_name="${BUILDKITE_PLUGIN_CREATE_ECR_NAME}"

upsert_ecr "${repository_name}"
